


server:
  port: 9999
spring:
  redis:
    timeout: 6000ms
    cluster:
      # 获取失败 最大重定向次数
      max-redirects: 3
      nodes: 192.168.140.128:6381,192.168.140.128:6382,192.168.140.128:6383,192.168.140.128:6384,192.168.140.128:6385,192.168.140.128:6386
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制），连接池在同一时间能够分配的最大连接数量
        max-active: 10
        # 连接池中的最大空闲连接,超过最大空闲连接数的连接将被释放，设置负数为不限制
        max-idle: 5
        # 连接池中的最小空闲连接。低于这个数量将创建新的连接。设置为0则不创建
        min-idle: 2
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

